# Counting

## Introduction

In @thm-equal, you showed that for a finite sample space with equally likely outcomes, our probability can be found by looking at the number of outcomes in the event of interest. So we need a good way to count those outcomes. Counting might sound easy, but sometimes there's a lot of subtlety in what we're trying to count.

## Definitions, Exercises, and Theorems

::: {#exr-spinroll}
As part of a game, I spin a spinner that is split equally among 3 colors (red, blue, and yellow), and I roll a fair four-sided die. How many combinations of spins and rolls could I get?
:::

::: {#exr-srprob}
In the scenario in @exr-spinroll, suppose the result I want is a red spin and a roll of either 3 or 4. What is the probability that I get my desired result?
:::

::: {#exr-pins}
Show that the number of four-digit PINs using digits 0 through 9 if digits can be reused is 10,000.
:::

::: {#exr-pins2}
How many four-digit PINs are there that do not use 2? What is the probability of choosing such a PIN from the set of all possible four-digit PINs?
:::

::: {#exr-password}
Suppose I have a set of $n$ characters and need a password of length $k$. I am allowed to reuse characters. Find and explain an expression for the number of possible passwords.
:::

::: {#exr-license}
Suppose a license plate format consists of 3 numbers (with repeats allowed) followed by 3 letters (again with repeats allowed). How many license plates are possible?
:::

::: {#exr-licenserep}
Now suppose that repeats are *not* allowed in the license plates described above. Each digit and each letter can be used at most once. How many license plates are possible?
:::

::: {#exr-prez}
All eight students in a class are going to give individual presentations during finals period. In how many possible orders could they present?
:::

::: {#nte-factorial .callout-note}
## Factorial

The **factorial** is a useful shorthand: $n$-factorial, or $n!$, is defined as $n! = n \cdot (n-1) \cdot \cdots 2 \cdot 1.$
:::

::: {#exr-prezperm}
On Thursday, only four of the students are going to give presentations, but they don't know in advance which four. How many possible ordered sets of four student presenters are there?
:::

::: {#nte-permutation .callout-note}
A **permutation** of $n$ objects is a way of ordering $n$ objects. A $k$-permutation from a set of size $n$ is a way of ordering $k$ objects chosen from a set of $n$ objects. $P(n,k)$ denotes the number of $k$-permutations from a set of size $n$.
:::

::: {#thm-perms}
Explain why the number of $k$-permutations from a set of size $n$ is $P(n,k) = \dfrac{n!}{(n-k)!}$.
:::

::: {#exr-bootstrap}
The “bootstrap” is a statistical method for generating a new data set that is like an existing one. Suppose we have a data set consisting of 6 observations: $x_1,x_2,x_3,x_4,x_5,x_6.$ To generate a bootstrap data set, we sample from the original data set with replacement, meaning that it is possible for each observation to be sampled more than once. An example bootstrap data set would be $x_2, x_3, x_4, x_2, x_1, x_3$. What is the probability that the bootstrap data set contains each observation exactly once?
:::

::: {#exr-playlist}
As I work in the evenings, I often listen to music. Suppose that I have a playlist of $n=50$ songs and I listen to them on shuffle where the software always selects from the list with equal probability when selecting which song to play next. If I listen to $k=10$ songs, what is the probability that at least one of the songs will be duplicated? What about if I listen to $k=30$ songs? (Hint: think about the complement of the desired probability!)
:::

::: {#exr-birthday}
There are $p$ people in the room. Assume that each person's birthday is equally likely to be any of 365 days (ignore leap years!) and that everyone's birthdays are independent. What is the probability that no one in the room has the same birthday? What is the least value of $p$ for which there is at least a 50% chance that two people do share a birthday?
:::

::: {#exr-countsubs}
Let $S = \{1,2,3,4,5\}$. Answer each of the following:

a.  How many ordered pairs with elements from $S$ are there?

b.  How many ordered triples with elements from $S$ are there?

c.  How many different two-element subsets of $S$ are there? (Recall that order does not matter in sets.)

d.  How many different three-element subsets of $S$ are there?

e.  How are the answers to (a) and (c) related? What about (b) and (d)?
:::

::: {#thm-comb}
Explain why the number of ways to pick a subset of size $k$ from a set of size $n$ is $\dfrac{n!}{k! (n-k)!}$.
:::

::: {#nte-combination .callout-note}
The **combination** $C(n,k)$ or $\binom{n}{k}$, usually read "$n$ choose $k$," is the number of ways to pick $k$ unordered things from a set of size $n$.
:::

::: {#exr-aces}
As part of a card game, I am dealt three cards from a standard 52-card deck. How many possible hands could I have? What is the probability that my hand does not contain an ace? (There are four aces in the deck.)
:::

::: {#exr-hhtt}
How many distinct sequences could I make using two copies of the letter $H$ and two copies of the letter $T$?
:::

::: {#exr-unfaircoin}
I flip an unfair coin with $P(H) = p$ four times. Find the probability that I flip exactly two tails. (Hint: What is the probability of the outcome $TTHH$? What about $HTHT$?)
:::

::: {#nte-binomial .callout-note}
A **Bernoulli trial** is a random experiment with two possible outcomes: success with probability $p$ or failure with probability $1-p$. A **binomial experiment** is a series of $n$ independent Bernoulli trials in which we count the number of successes.
:::

::: {#thm-binom}
Explain why the probability of $k$ successes in a binomial experiment is $$P(k) = \binom{n}{k} p^k (1-p)^{n-k}.$$
:::

::: {#exr-parkinsons}
A woman, Joy, claimed that she could smell Parkinson's disease. Researchers gave her 12 shirts and asked her to identify which ones had been worn by someone with Parkinson's. Initially, researchers believe that she correctly identified 11 of the shirts. If she had been randomly guessing, what is the probability that she would have identified **at least** 11 of the shirts correctly? Based on this, do you believe her claim or not? (When you're done with the problem, I'll tell you what happened next!)
:::

::: {#exr-tennis}
A particular tennis player has a first serve percentage (which means his attempt at serving the ball lands in a valid place) across his career of 65%. In one set, 17 of his 18 first serves were valid. What is the probability of this player serving at least this well across 18 first serves?
:::

::: {#exr-coprez}
A club needs to choose two co-presidents. The names of all the current members are put into a hat, and the first two that are drawn will be co-presidents. The names are not replaced once they are drawn (one person cannot be two presidents). You want to know the probability that the presidents both have the same major. Is this binomial, and why/why not?
:::

## Further Practice

To come!

## Challenge Questions

::: {#exr-setgame}
The game SET involves a deck of 81 cards. Each card has a picture of some number (one, two, or three) of shapes (oval, squiggle, or diamond), which is painted in one color (green, red, or purple), with some shading (solid, hatched, or empty). Each number-shape-color-shading combination appears in the deck exactly once. Three cards are called a set if for each attribute, either all three cards match or all three are different. (For example, for color, either all three cards need to be the same color, or they each need to be a different color.) How many different sets are in the deck? What is the probability of there being a set in the first 4 cards dealt from a well-shuffled deck?
:::

::: {#exr-mail}
A mail carrier delivers mail to nineteen houses on the east side of Blossom Street. The carrier notes that no two adjacent houses ever get mail on the same day, but that there are never more than two houses in a row that get no mail on the same day. How many different patterns of mail delivery are possible?[^counting-1]
:::

[^counting-1]: From AIME 2011 CITE
