# Set Theory

## Introduction

In INTRODUCTION, I said that we'd define probability as a function that follows some rules. But functions need some kind of input and output, so we need to start there. We'll say that a function maps from a **set** $X$ to a set $Y$. This chapter is all about what we mean by a **set** and how these sets behave.

## Definitions, Exercises, and Theorems

::: {#nte-set .callout-note}
## Set

A **set** $A$ is an unordered list of elements. We commonly describe $A$'s elements in two ways.

- **Roster notation** lists the elements: $\{a_1, a_2, \cdots a_n\}$

- **Set-builder notation** uses a condition that exactly describes the elements of $A$. For example, the set of positive integers less than 20 could be written as $A = \{a |~ a \in \mathbb{Z}^+, a < 20\}.$
:::

::: {#nte-subset .callout-note}
## Element and Subset

If $t$ is an element of set $A$, then we say that $t$ is an **element** of $A$, that $t$ is **in** $A$, or $t \in A$. If every element of a set $B$ is also in $A$, then we say that $B$ is a **subset** of $A$, or $B \subseteq A$.
:::

For example, $\{2,4\}$ is a subset of $\{1,2,3,4,5\}$, but $\{4,6\}$ is not. The empty set $\emptyset$ (the set of no elements) is considered a subset of all sets. A set is also considered a subset of itself.

::: {#exr-writeset}
Let $A = \{n \mid n = 4k+1, k \in \mathbb{Z}\}$ and let $B = \{2, 5, 8, 11, 14, 17, 20\}$. Choose and write a non-empty subset of $A$ in roster notation, and choose and write a non-empty subset of $B$ in set-builder notation.
:::

::: {#nte-equality .callout-note}
## Set Equality

We say that two sets $A$ and $B$ are **equal**, or $A = B$, if they have exactly the same elements. This is equivalent to both $A \subseteq B$ and $B \subseteq A$ being true.
:::

::: {#exr-equality}
Use the definition of set equality to show that $A = C$ where $A = \{n \mid n = 4k+1, k \in \mathbb{Z}\}$ and $B = \{m \mid m = 4l - 3, l \in \mathbb{Z}\}$. (There are other ways to show this, but this exercise is about practicing using the definition!)
:::

::: {#nte-cupcap .callout-note}
## Union and Intersection

Given sets $A$ and $B$, their union $A \cup B$ is the set of all elements that are in at least one of $A$ or $B$. Given $n$ sets $A_1, A_2, \cdots, A_n$, their union $\bigcup_{i=1}^n A_i = A_1 \cup A_2 \cup \cdots \cup A_n$ is the set of all elements that are in at least one of the original $n$ sets.

The intersection of $A$ and $B$, denoted $A \cap B$, is the set of all elements that are in both $A$ and $B$. The intersection of $n$ sets $\bigcap_{i=1}^n A_i = A_1 \cap A_2 \cap \cdots \cap A_n$ is the set of all elements that are in every one of the original $n$ sets.
:::

For example, $\{1,2,3,4,5\} \cup \{4,6\} = \{1,2,3,4,5,6\}$, and $\{1,2,3,4,5\} \cap \{4,6\} = \{4\}$.

::: {#exr-cupcap}
Find the intersection of $A$ and $B$ from @exr-writeset. Find the union of the subsets of $A$ and $B$ that you described in @exr-writeset.
:::

::: {#exr-cupcap3}
Define three sets $A_1$, $A_2$, and $A_3$ of your choosing, and find their union $\bigcup_{i=1}^3 A_i$ and their intersection $\bigcap_{i=1}^3 A_i$.
:::

::: {#exr-distpt1}
Show that $A \cap (B \cup C) \subseteq (A \cap B) \cup (A \cap C)$.
:::

::: {#thm-dist}
## Distributive Law

Prove the following visually, and then prove them using the definition of set equality (@nte-equality). (You're already halfway there on the first statement with @exr-distpt1!)

For any sets $A, B,$ and $C$, we have that

- $A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$;

- $A \cup (B \cap C) = (A \cup B) \cap (A \cup C)$.
:::

::: {#nte-compdiff .callout-note}
We call a set $S$ the **universal set** if it is the set of all elements that we are considering to be possible in a particular context.

Given a set $A \subseteq S$, the **complement** of $A$, denoted $A^C$ or $\bar{A}$, is the set of all elements of $S$ not in $A$.

Given two sets $A$ and $B$, the **difference** $A-B$ is the set of all elements of $A$ that are not in $B$.
:::

::: {#exr-compdiff}
Let $S = \{0, 2, 4, 6, 8, 10\}$, $A = \{0, 4, 8\}$, and $B = \{0, 2, 8, 10\}$. Find $A^C$, $B^C$, $A-B$, and $B-A$.
:::

::: {#thm-demorgan}
## DeMorgan's Laws

Prove the following for the case $n=2$ or $n=3$. (If you've seen induction, try proving it for a general natural number $n$ using @nte-equality!) For any sets $A_1, A_2, \cdots, A_n$, we have that

- $\left(A_1 \cup A_2 \cup \cdots \cup A_n\right)^C = A_1^C \cap A_2^C \cap \cdots \cap A_n^C$;
- $\left(A_1 \cap A_2 \cap \cdots \cap A_n\right)^C = A_1^C \cup A_2^C \cup \cdots \cup A_n^C$.
:::

::: {#nte-partition .callout-note}
## Disjoint and Partition

Sets $A$ and $B$ are **disjoint** if they have no elements in common, that is, if $A \cap B = \emptyset$.

A **partition** of a set $S$ is a collection of sets $A_1, A_2, \cdots, A_n \subseteq S$ such that $A_1, A_2, \cdots A_n$ are all pairwise disjoint (no two of the sets share an element) and $A_1 \cup A_2 \cup \cdots \cup A_n = S$.
:::

::: {#exr-partition}
Let $S = \{1,2,3\}$. Write all possible partitions of $S$, and explain how you know that these are all the possibilities.
:::

::: {#exr-cardpart}
Let $S$ be the set of all cards in a standard 52-card deck. Let $A$ be the set containing the clubs and the red face cards. Describe a set $B$ such that $A$ and $B$ are disjoint. Do $A$ and your set $B$ form a partition of $S$? Explain.
:::

::: {#nte-bijection .callout-note}
## Bijection

A **bijection** between sets $A$ and $B$ is a function $f: A \rightarrow B$ such that for each element $b \in B$, there is exactly one element $a \in A$ such that $f(a) = b$.
:::

::: {#exr-bij}
Describe or illustrate a bijective function $f: A \rightarrow B$ where $A = \{\textrm{red, blue, yellow}\}$ and $B = \{\textrm{shirt, skirt, headband}\}$.
:::

::: {#nte-cardinality .callout-note}
## Cardinality

The **cardinality** of a set $A$, denoted $|A|$, is a measure of the size of the set. If $A$ is the empty set, then $|A| = 0$. If there is a bijection between $A$ and the set $\{1, 2, \cdots, n\}$ for some positive integer $n$, then $|A| = n$. (This means that for finite sets, the cardinality is the number of elements in the set.) In general, two sets have the same cardinality if there is a bijection between them.
:::

::: {#exr-partcard}
Suppose that $A_1$, $A_2$, and $A_3$ form a partition of a universal set $S$. Let $B$ be some other set. If we know that $|B \cap A_1| = n$, $|B \cap A_2| = m$, and $|B \cap A_3| = k$, what is $|B|$ and why?
:::

::: {#nte-infinity .callout-note}
## Countable and Uncountable

A set $A$ is called **countable** if it is either finite or in one-to-one correspondence with the natural numbers $\mathbb{N}$. (In other words, a set $A$ is countably infinite if we can find some bijection between it and $\mathbb{N}$, matching each element of $A$ to exactly one element of $\mathbb{N}$.)

A set is called **uncountable** if it is not countable. For example, the real numbers $\mathbb{R}$ are uncountable, as are all intervals such as $(0,1)$.
:::

::: {#exr-interval}
Find a bijection between the interval $(0,1)$ and the interval $(3,5)$.
:::

::: {#exr-uncountable}
Using that $(0,1)$ is uncountable, prove that any open interval $(a,b)$ with $a<b$ and $a, b \in \mathbb{R}$ is uncountable. (Hint: generalize your work from @exr-interval.)
:::

::: {#thm-pie}
Let $A$ and $B$ be finite sets. Prove that $|A \cup B| = |A| + |B| - |A \cap B|$.
:::

::: {#exr-pie}
How would you generalize the previous theorem to give the cardinality of the union of three finite sets $|A \cup B \cup C|$ instead of just two? What about $n$ finite sets?
:::

::: {#exr-olypie}
Suppose that a survey of Summer Olympics viewers in the US showed the following:

- 50% watched gymnastics;

- 80% watched track;

- 10% watched diving;

- 9% watched diving and gymnastics;

- 7% watched diving and track;

- 40% watched gymnastics and track;

- 6% watched all three.

Find the percentage of the group that watched none of these three sports.
:::

## Further Practice

To come!

## Challenge Questions

To come!
